import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({jobs}) {
 console.log(jobs)
  return (
    <>
      <Head>
        <title>All Jobs in Nepal</title>
        <meta name="description" content="Generated by All Jobs in Nepal" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
           All Jobs In Nepal
          </p>
        </div>

        <div className={styles.grid}>
          {jobs.map((post)=> <div>
           
          
          <a
          href='#' className={styles.card}
            
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
            {post.job_title} <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             {post.company_name}
            </p>
          </a>
          </div>)}

        </div>
      </main>
    </>
  )
}


export async function getStaticProps() {
  var res = await fetch(`http://127.0.0.1:8000`);
  const response = await res.json();
  const jobs = response.message

  return {
    props: {
      jobs,
    },
    revalidate: 10, // Revalidate every 10 seconds with new data.
  };
}